version: "2"
linters:
  default: all
  disable:
    - canonicalheader
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - godot
    - gomoddirectives
    - intrange
    - ireturn
    - mnd
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - revive
    - tagliatelle
    - testifylint
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 15
      package-average: 0
    funlen:
      lines: 80
      statements: 50
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gocognit
          - lll
        path: _test\.go
      - linters:
          - funlen
          - lll
        source: "^// "
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
