// Code generated by "enumer -type=ChainID -linecomment -json=true -sql=true -yaml"; DO NOT EDIT.

package chains

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _ChainIDName = "ethereumoptimismcronosbscetctomognosisvelaspolygonbttcfantomkccmoonbeamkavacantoklaytnethwfusionarbitrumcelooasisavaxaurora"
const _ChainIDLowerName = "ethereumoptimismcronosbscetctomognosisvelaspolygonbttcfantomkccmoonbeamkavacantoklaytnethwfusionarbitrumcelooasisavaxaurora"

var _ChainIDMap = map[ChainID]string{
	1:          _ChainIDName[0:8],
	10:         _ChainIDName[8:16],
	25:         _ChainIDName[16:22],
	56:         _ChainIDName[22:25],
	61:         _ChainIDName[25:28],
	88:         _ChainIDName[28:32],
	100:        _ChainIDName[32:38],
	106:        _ChainIDName[38:43],
	137:        _ChainIDName[43:50],
	199:        _ChainIDName[50:54],
	250:        _ChainIDName[54:60],
	321:        _ChainIDName[60:63],
	1284:       _ChainIDName[63:71],
	2222:       _ChainIDName[71:75],
	7700:       _ChainIDName[75:80],
	8217:       _ChainIDName[80:86],
	10001:      _ChainIDName[86:90],
	32659:      _ChainIDName[90:96],
	42161:      _ChainIDName[96:104],
	42220:      _ChainIDName[104:108],
	42262:      _ChainIDName[108:113],
	43114:      _ChainIDName[113:117],
	1313161554: _ChainIDName[117:123],
}

func (i ChainID) String() string {
	if str, ok := _ChainIDMap[i]; ok {
		return str
	}
	return fmt.Sprintf("ChainID(%d)", i)
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ChainIDNoOp() {
	var x [1]struct{}
	_ = x[Ethereum-(1)]
	_ = x[Optimism-(10)]
	_ = x[Cronos-(25)]
	_ = x[BSC-(56)]
	_ = x[ETC-(61)]
	_ = x[Tomo-(88)]
	_ = x[Gnosis-(100)]
	_ = x[Velas-(106)]
	_ = x[Polygon-(137)]
	_ = x[BTTC-(199)]
	_ = x[Fantom-(250)]
	_ = x[KCC-(321)]
	_ = x[Moonbeam-(1284)]
	_ = x[Kava-(2222)]
	_ = x[Canto-(7700)]
	_ = x[Klaytn-(8217)]
	_ = x[EthereumPow-(10001)]
	_ = x[Fusion-(32659)]
	_ = x[Arbitrum-(42161)]
	_ = x[Celo-(42220)]
	_ = x[Oasis-(42262)]
	_ = x[Avax-(43114)]
	_ = x[Aurora-(1313161554)]
}

var _ChainIDValues = []ChainID{Ethereum, Optimism, Cronos, BSC, ETC, Tomo, Gnosis, Velas, Polygon, BTTC, Fantom, KCC, Moonbeam, Kava, Canto, Klaytn, EthereumPow, Fusion, Arbitrum, Celo, Oasis, Avax, Aurora}

var _ChainIDNameToValueMap = map[string]ChainID{
	_ChainIDName[0:8]:          Ethereum,
	_ChainIDLowerName[0:8]:     Ethereum,
	_ChainIDName[8:16]:         Optimism,
	_ChainIDLowerName[8:16]:    Optimism,
	_ChainIDName[16:22]:        Cronos,
	_ChainIDLowerName[16:22]:   Cronos,
	_ChainIDName[22:25]:        BSC,
	_ChainIDLowerName[22:25]:   BSC,
	_ChainIDName[25:28]:        ETC,
	_ChainIDLowerName[25:28]:   ETC,
	_ChainIDName[28:32]:        Tomo,
	_ChainIDLowerName[28:32]:   Tomo,
	_ChainIDName[32:38]:        Gnosis,
	_ChainIDLowerName[32:38]:   Gnosis,
	_ChainIDName[38:43]:        Velas,
	_ChainIDLowerName[38:43]:   Velas,
	_ChainIDName[43:50]:        Polygon,
	_ChainIDLowerName[43:50]:   Polygon,
	_ChainIDName[50:54]:        BTTC,
	_ChainIDLowerName[50:54]:   BTTC,
	_ChainIDName[54:60]:        Fantom,
	_ChainIDLowerName[54:60]:   Fantom,
	_ChainIDName[60:63]:        KCC,
	_ChainIDLowerName[60:63]:   KCC,
	_ChainIDName[63:71]:        Moonbeam,
	_ChainIDLowerName[63:71]:   Moonbeam,
	_ChainIDName[71:75]:        Kava,
	_ChainIDLowerName[71:75]:   Kava,
	_ChainIDName[75:80]:        Canto,
	_ChainIDLowerName[75:80]:   Canto,
	_ChainIDName[80:86]:        Klaytn,
	_ChainIDLowerName[80:86]:   Klaytn,
	_ChainIDName[86:90]:        EthereumPow,
	_ChainIDLowerName[86:90]:   EthereumPow,
	_ChainIDName[90:96]:        Fusion,
	_ChainIDLowerName[90:96]:   Fusion,
	_ChainIDName[96:104]:       Arbitrum,
	_ChainIDLowerName[96:104]:  Arbitrum,
	_ChainIDName[104:108]:      Celo,
	_ChainIDLowerName[104:108]: Celo,
	_ChainIDName[108:113]:      Oasis,
	_ChainIDLowerName[108:113]: Oasis,
	_ChainIDName[113:117]:      Avax,
	_ChainIDLowerName[113:117]: Avax,
	_ChainIDName[117:123]:      Aurora,
	_ChainIDLowerName[117:123]: Aurora,
}

var _ChainIDNames = []string{
	_ChainIDName[0:8],
	_ChainIDName[8:16],
	_ChainIDName[16:22],
	_ChainIDName[22:25],
	_ChainIDName[25:28],
	_ChainIDName[28:32],
	_ChainIDName[32:38],
	_ChainIDName[38:43],
	_ChainIDName[43:50],
	_ChainIDName[50:54],
	_ChainIDName[54:60],
	_ChainIDName[60:63],
	_ChainIDName[63:71],
	_ChainIDName[71:75],
	_ChainIDName[75:80],
	_ChainIDName[80:86],
	_ChainIDName[86:90],
	_ChainIDName[90:96],
	_ChainIDName[96:104],
	_ChainIDName[104:108],
	_ChainIDName[108:113],
	_ChainIDName[113:117],
	_ChainIDName[117:123],
}

// ChainIDString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ChainIDString(s string) (ChainID, error) {
	if val, ok := _ChainIDNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ChainIDNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ChainID values", s)
}

// ChainIDValues returns all values of the enum
func ChainIDValues() []ChainID {
	return _ChainIDValues
}

// ChainIDStrings returns a slice of all String values of the enum
func ChainIDStrings() []string {
	strs := make([]string, len(_ChainIDNames))
	copy(strs, _ChainIDNames)
	return strs
}

// IsAChainID returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ChainID) IsAChainID() bool {
	_, ok := _ChainIDMap[i]
	return ok
}

// MarshalJSON implements the json.Marshaler interface for ChainID
func (i ChainID) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ChainID
func (i *ChainID) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ChainID should be a string, got %s", data)
	}

	var err error
	*i, err = ChainIDString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for ChainID
func (i ChainID) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for ChainID
func (i *ChainID) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ChainIDString(s)
	return err
}

func (i ChainID) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *ChainID) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of ChainID: %[1]T(%[1]v)", value)
	}

	val, err := ChainIDString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
